package lib

const (
	RINGSERVER_IP            = "localhost"
	RINGSERVER_NODES_PORT    = "5001"
	RINGSERVER_SECOND_NODES_PORT = "5002"
	RINGSERVER_FRONTEND_PORT = "3001"
	REPLICATION_FACTOR       = 3
	MAX_KEYS                 = 10
)
